# 1. 御神籤
実行するだけでおみくじが引けます。<br>
分配は浅草寺の割合を参照しており、凶30%、大吉17%、吉35%、半吉5%、小吉4%、末小吉3%、末吉6%です。

In [36]:
import numpy as np

# 御神籤の結果と確率のリスト
omikuji_results = [
  # (閾値, 結果)
    (0.17, "大吉"),
    (0.52, "吉"),
    (0.57, "半吉"),
    (0.61, "小吉"),
    (0.64, "末小吉"),
    (0.70, "末吉"),
    (1.00, "凶")
]

# 御神籤を引く処理
def omikuji_draw():
    kuji = np.random.rand()
    # print(f"{kuji}"") #デバッグ用

    for threshold, result in omikuji_results:
        if kuji <= threshold:
            print(f"あなたの運勢は「{result}」です")
            return

omikuji_draw()

あなたの運勢は「大吉」です


# 2. サイコロシミュレーター
サイコロを好きな回数だけ振って、結果と統計情報を表示します。

In [ ]:
import numpy as np

def dice_simulater():
  print("--- サイコロシミュレータ ー---")

  while True:

    # 不具合対策
    try:
      num_times = int(input("サイコロを振る回数を入力してください。（プログラムを終了: 0）"))
      if num_times == 0:
        print("プログラムを終了します。")
        break
      if num_times < 1:
        print("1以上の数を入力してください")
        continue

        # サイコロの出目生成と結果表示
      times = np.random.randint(1, 7, num_times)
      print(f"{num_times}回: {times}")
      print(f"合計: {np.sum(times)}")
      print(f"平均: {np.mean(times)}")
      print(f"中央値: {np.median(times)}")
      print(f"標準偏差: {np.std(times)}")
      print(f"分散: {np.var(times)}")
      print(f"最大値,最小値: {np.max(times)},{np.min(times)}")
      print(f"相関係数行列: {np.unique(times)}")
      print(f"-" * 30)

    except ValueError:
      print("無効な入力です。数字を入力してください。")

dice_simulater()

--- サイコロシミュレータ ー---
1サイコロを振る回数を入力してください。（プログラムを終了:0）10
10回: [5 3 3 5 3 2 4 1 1 6]
合計: 33
平均: 3.3
中央値: 3.0
標準偏差: 1.6155494421403513
分散: 2.6100000000000003
最大値,最小値: 6,1
相関係数行列: [1 2 3 4 5 6]
------------------------------
1サイコロを振る回数を入力してください。（プログラムを終了:0）0
プログラムを終了します。


# 3.コイン投げシミュレーター
コイン投げをシミュレートし、表と裏の回数をカウントします。

In [ ]:
import numpy as np

def coin_flip_simulater():
  print("---- コイン投げシミュレーター ---")
  while True:

    # 不具合対策
    try:
      num_flips = int(input("コインを投げる回数を入力してください。（プログラムを終了: 0）"))
      if num_flips == 0:
        print("プログラムを終了します。")
        break
      if num_flips < 1:
        print("1以上の数を入力してください。")
        continue

        # コインの表裏生成と回数計算
      results = np.random.choice(["表", "裏"], size = num_flips, p = [0.5, 0.5])
      flont_count = np.sum(results == "表")
      back_count = np.sum(results == "裏")

      flont_ratio = flont_count / num_flips
      back_ratio = back_count / num_flips

      print(f" /n{num_flips}回投げて...")
      print(f"表: {flont_count}回")
      print(f"裏: {back_count}回")
      print(f"表の割合: {flont_ratio:.2%}")
      print(f"裏の割合: {back_ratio:.2%}")
      print("_" * 30)

    except ValueError:
      print("無効な入力です。数字を入力してください。")

coin_flip_simulater()

---- コイン投げシミュレーター ---
コインを投げる回数を入力してください。（プログラムを終了: 0）100
 /n100回投げて...
表: 46回
裏: 54回
表の割合: 46.00%
裏の割合: 54.00%
______________________________
コインを投げる回数を入力してください。（プログラムを終了: 0）10000
 /n10000回投げて...
表: 5009回
裏: 4991回
表の割合: 50.09%
裏の割合: 49.91%
______________________________
コインを投げる回数を入力してください。（プログラムを終了: 0）100000
 /n100000回投げて...
表: 50153回
裏: 49847回
表の割合: 50.15%
裏の割合: 49.85%
______________________________
コインを投げる回数を入力してください。（プログラムを終了: 0）0
プログラムを終了します。


# 4.テンソル神経衰弱
不規則に生成されたテンソルを使った神経衰弱のようなゲームです。<br>
### ルール
1. ランダムなテンソルAとBが表示されます。
2. もしAとBが全く同じなら「y」を、違うなら「n」を入力してください。

In [14]:
import torch
import time
import numpy as np

def tensor_memory_game():
  print("--- テンソル神経衰弱 ---")

  while True:
    # ランダムな2×2テンソルを生成
    tensor_A = torch.rand(2,2).round()

    if np.random.rand() < 0.3:  #30%の確率でAと同じテンソルにする
      tensor_B = tensor_A .clone()

    else:
      tensor_B = torch.rand(2,2).round()

    print("\nテンソルA:\n", tensor_A)
    print("\nテンソルB:\n", tensor_B)

    user_judgment = input("\nテンソルAとBは同じですか？（y/nで回答, qで終了:）").lower()
    are_equal = torch.equal(tensor_A, tensor_B)

    if user_judgment == "q":
      print("プログラムを終了します")
      break

    if (user_judgment == "y" and are_equal) or (user_judgment == "n" and not are_equal):
      print("正解です！")

    else:
      print(f"不正解です...。正解は{'Yes'if are_equal else'No'}です")

    time.sleep(1)
    print("\n次の問題")



tensor_memory_game()

--- テンソル神経衰弱 ---

テンソルA:
 tensor([[0., 0.],
        [0., 1.]])

テンソルB:
 tensor([[1., 0.],
        [1., 0.]])

テンソルAとBは同じですか？（y/nで回答, qで終了:）y
不正解です...。正解はNoです

次の問題

テンソルA:
 tensor([[0., 1.],
        [0., 0.]])

テンソルB:
 tensor([[1., 0.],
        [1., 0.]])

テンソルAとBは同じですか？（y/nで回答, qで終了:）n
正解です！

次の問題

テンソルA:
 tensor([[0., 1.],
        [0., 1.]])

テンソルB:
 tensor([[0., 1.],
        [0., 0.]])

テンソルAとBは同じですか？（y/nで回答, qで終了:）q
プログラムを終了します


# 5. ラッキーナンバー占い

In [91]:
import torch

# 素数判定
def is_prime(n):
  if n < 2:
    return False
  if n == 2:
    return True
  if n % 2 == 0:
    return False

  i = 3
  while i * i <= n:
    if n % i == 0:
      return False
    i +=2
  return True

#ラッキーナンバー占い
def lucky_number_fortune():
  print("--- 今日のラッキーナンバー占い ---")

  # ラッキーナンバー生成
  lucky_number = torch.randint(1, 101, (1,)).item()
  print(f"\nあなたの今日のラッキーナンバーは{lucky_number}です！")

  # 数字から運勢を説明
  if lucky_number % 2 == 0:
    print("偶数には、常に2で割り切れるという安心感があります。きっと安全で調和の取れた一日になるでしょう。")

  else:
    print("奇数には、素数である可能性が秘められています。新たな道を切り開けるかも知れない、そんな一日になるでしょう。")
    if is_prime(lucky_number):
      print("なんと、あなたのラッキーナンバーは素数です！どんな自然数も、素数の積で表すことができます。きっと神秘的な一日になるでしょう。")

    if lucky_number == 7:
      print("「7」という数字は、多くの人から幸運の数字と信じられています。きっと最高の一日になるでしょう。")
    if lucky_number == 18:
      print("「18」という数字は、十八番という概念にも組み込まれています。自分の得意とする芸や技が、より輝く一日になるでしょう。")

lucky_number_fortune()

--- 今日のラッキーナンバー占い ---

あなたの今日のラッキーナンバーは44です！
偶数には、常に2で割り切れるという安心感があります。きっと安全で調和の取れた一日になるでしょう。
